clear; clc;
close all

filesToConsider = 'all'; % other options: MB, DB, all, *specific file*
disp(['Part of the machine being considered: ' char(filesToConsider)]) ;

magnetFamilies = { % 'all'...
% % Magnets MB:
                    'D1'; ...
                    'D2T1';...
%                     'D2T2';...
%                     'D3';...
%                     'D4';...
%                     'Q1';...
%                     'Q2';...
%                     'Q3T1';...
%                     'Q3T2';...
%                     'Q3T3';...
%                     'Q4T1';...
%                     'Q4T2';...
%                     'Q4T3';...
%                     'Q5';...
%                     'SX1';...
%                     'SX2';...
% % % %
% % Magnets DB:
%                     'COMBINED_FUNCTION_CR1';...
%                     'COMBINED_FUNCTION_CR2';...
%                     'COMBINED_FUNCTION_DL';...
%                     'MB1';...
%                     'MB2';...
%                     'MB3';...
%                     'Q1';...
%                     'Q1++';...
% %                     'Q4';... % Files are missing !!
%                     'QLINAC';...
%                     'QLINAC--';...
%                     'SX';...
%                     'SX2';...
%                     'SX2++';...
                } ; % other options: 'all'
tmp = [] ;
for i = 1:size(magnetFamilies,1)
    if i>1
        tmp = [tmp ', '];
    end
    tmp = [ tmp char(magnetFamilies(i,:)) ] ;
end
    disp(['Magnet families being considered: ' tmp]);
clear tmp

dip_max_strength = 3e50 ;
quad_max_strength = 30e50 ;
sext_max_strength = 3000e50 ;

%%

% Import files
data = import_files(filesToConsider) ;
disp([ 'Total elements [#]: ' num2str(size(data,1))]);

% Select magnet family
data = select_data(data,magnetFamilies) ;
disp([ 'Selected elements (family, part of machine) [#]: ' num2str(size(data,1))]);

% Filter out impossible Permanent Magnets
data = filter_out_impossible_PM(data,dip_max_strength,quad_max_strength,sext_max_strength) ;
disp([ 'Filtered elements (only possible PM) [#]: ' num2str(size(data,1))]);

% Plot data
plot_data(data,magnetFamilies) ;


%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Magnets overview

showOverview = 'MB'; %other options: 'DB', 'all'

