function [] = show_bars(partMachine)
switch partMachine
    case 'MB'
        MB_magnets=[{'D1';...
            'D2T1';...
            'D2T2';...
            'D3';...
            'D4';...
            'Q1';...
            'Q2';...
            'Q3T1';...
            'Q3T2';...
            'Q3T3';...
            'Q4T1';...
            'Q4T2';...
            'Q4T3';...
            'Q5';...
            'SX1';...
            'SX2'}] ;
        filesToConsider = 'MB';
        data = import_files(filesToConsider) ;
        for i = 1:size(MB_magnets,1)
            tmp = select_data(data,MB_magnets{i,:});
            yy(i) = size(tmp,1);
        end
        c = categorical (MB_magnets);
        figure
        bar(c,yy);
        title('Magnets in MB');
        grid on
    case 'DB'
        DB_magnets =[{'COMBINED_FUNCTION_CR1';...
            'COMBINED_FUNCTION_CR2';...
            'COMBINED_FUNCTION_DL';...
            'MB1';...
            'MB2';...
            'MB3';...
            %'MBCO';...
            %'MBCO2';...
            'Q1';...
            'Q1++';...
            'Q4';...
            'QLINAC';...
            'QLINAC--';...
            'SX';...
            'SX2';...
            'SX2++'}] ;
        filesToConsider = 'DB';
        data = import_files(filesToConsider) ;
        for i = 1:size(DB_magnets,1)
            tmp = select_data(data,DB_magnets{i,:});
            yy(i) = size(tmp,1);
        end
        c = categorical (DB_magnets);
        figure
        bar(c,yy);
        title('Magnets in DB');
        grid on
    case 'all'
        all_magnets = [{'COMBINED_FUNCTION_CR1';...
            'COMBINED_FUNCTION_CR2';...
            'COMBINED_FUNCTION_DL';...
            'MB1';...
            'MB2';...
            'MB3';...
            %'MBCO';...
            %'MBCO2';...
            'D1';...
            'D2T1';...
            'D2T2';...
            'D3';...
            'D4';...
            'Q1';...
            'Q1++';...
            'Q2';...
            'Q3T1';...
            'Q3T2';...
            'Q3T3';...
            'Q4T1';...
            'Q4T2';...
            'Q4T3';...
            'Q4';...
            'Q5';...
            'QLINAC';...
            'QLINAC--';...
            'SX1';...
            'SX2';...
            'SX2++'}] ;
        filesToConsider = 'all';
        data = import_files(filesToConsider) ;
        for i = 1:size(all_magnets,1)
            tmp = select_data(data,all_magnets{i,:});
            yy(i) = size(tmp,1);
        end
        c = categorical (all_magnets);
        figure
        bar(c,yy);
        title('All CLIC magnets');
        grid on
end
end

